### ISSUE TITLE
Why do we unignore plugins

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-bootstrapper#11]
When we add a custom plugin url in `october.yaml` with`bareRepo: true ` 
The `.gitignore` is edited to unignore these folders. 

Each time I have to remove this lines. IMO when we add bareRepo we shouldn't keep anything from custom plugins in CVS. 

What do you think ?

**Comment by tobias-kuendig** [comment]
We use this functionality internally since our custom plugins are often just a "shell" that gets tailored to a client's needs. So often we install the private plugin once, change it and commit it to the customer's repo.

But I see your point. I guess it makes sense to add an option to ignore the plugins completely and then later install them manually via CI on the server.

I'll implement something.

**Comment by tobias-kuendig** [comment]
Added in 0.2.11

See https://github.com/OFFLINE-GmbH/oc-bootstrapper#excludeplugins

Thank you for your input!

**Comment by Adrion** [comment]
Niiice i'll check this :) 
Thanks !
