### ISSUE TITLE
october update command

### ISSUE THREAD

**Issue by tomaszstrojny** [OFFLINE-GmbH/oc-bootstrapper#27]
Hi,

I am pretty new to the `oc-bootstrapper`, but I really like the concept and would like to contribute a little. Right now I am writing because I just want to ensure that I understand the basic concept.

I understand the typical workflow while using `oc-boostrapper` is (as you described in a different issue):
1. Add new plugin to `october.yml`
1. Push to Git repo
1. Our CI system deploys the new code to the server and runs `october install` which picks up the new plugin from the configuration file and installs it.

This works great when we have an empty directory and want to install OctoberCMS there. I do understand `.gitignore`ing the private plugins but on the other hand I cannot get why you have decided to remove git repositories from plugins. To be honest I think that almost whole application should be `.gitignore`d so that updates were controlled by composer and October's console commands or at least whole `plugins` directory. 

I guess there is a reason but I just can't figure it out.

I would like to take some steps towards `october update` command so that whole October gets updated. I mean October core, all plugins from marketplace, private plugins and themes. And I think there's a great tool from October core `php artisan october:util git pull` which walks through all plugins and themes that has a `.git` directory and pulls them. With SSH key and SSH agent it is a very nice and painless way to pull all the private plugins and theme which I personally do quite often.

Let me know if I understand the concept right, is there any progress on `october update` command and if you like to see my help here.

Thanks in advance,

Tomasz Strojny

**Comment by tobias-kuendig** [comment]
Hi Tomasz

Did you take a look at the `excludePlugins` options? I'm not actively using it but it essentially re-downloads all plugins when running `october install` (what would result to a hacky but working update process).

We don't update private plugins since we open source everything of general interest and only checkout "template" plugins for customers that will then be modified to the project's need. This is why we don't necessarily want/need updates to private plugins.

But I understand that it is needed in other circumstances. If you have concrete suggestions please feel free to post them. We are generally open to extensions to oc-bootstrapper.

Regarding October updates, we moved that part into our deployment script. It runs `php artisan october:update` once a day.

```bash
    cd project_dir

    git pull
    [ ! -f "composer.phar" ] && wget https://getcomposer.org/composer.phar
    php composer.phar install --no-interaction --no-dev --prefer-dist
    php ./vendor/bin/october install
    php artisan -v october:up

    ## START UPDATE CHECK
    LOCK_FILE=".last-update-check"
    NOW=$(date +%s)
    LAST_CHECK=$( [ -f $LOCK_FILE ] && cat $LOCK_FILE || echo 0 )
    SECONDS_SINCE=$(expr $NOW - $LAST_CHECK)

    if [ "$SECONDS_SINCE" -gt "86400" ]; then
        HOSTNAME=$( hostname )
        GIT=$( which git )

        php composer.phar update
        php artisan -v october:update

        if [[ -n $(git status -s) ]]; then
            $GIT add --all .
            $GIT commit -m "[ci skip] oc-bootstrapper updated October CMS"
            $GIT push origin master
        fi

        echo $NOW > $LOCK_FILE
    else
        echo "Skipping update check (last check was $SECONDS_SINCE seconds ago)"
    fi
    ## END UPDATE CHECK

    git status -s
```

**Comment by czerwonyd** [comment]
According to the talking, here's my PR:

https://github.com/OFFLINE-GmbH/oc-bootstrapper/pull/28
