### ISSUE TITLE
Running from the local vendor folder

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-bootstrapper#43]
I tried to install the oc-bootstrapper only in the local folder for a project and tried to use the `vendor/bin/october` binary which is automatically created by composer. However, when doing this, pathes seem incorrect to the autoload file:

```
ploi@zeus-temple:~/foobar.com$ vendor/bin/october -v
PHP Warning:  require(/home/ploi/foobar.com/vendor/offline/oc-bootstrapper/vendor/autoload.php): failed to open stream: No such file or directory in /home/ploi/foobar.com/vendor/offline/oc-bootstrapper/october on line 8
PHP Fatal error:  require(): Failed opening required '/home/ploi/foobar.com/vendor/offline/oc-bootstrapper/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/ploi/foobar.com/vendor/offline/oc-bootstrapper/october on line 8
```

The issue seems to be [here](https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/october#L5-L9), as if the location of `autoload.php` is exactly one dir above (as in this case), it wont match...

**Comment by tobias-kuendig** [comment]
That's strange. I do use the local binary in almost every project I deploy and never had this issue.

`__DIR__` in my case equals to `/home/offline/project/vendor/offline/oc-bootstrapper`.

`file_exists(__DIR__.'/../../autoload.php')` is `true` since the autoloader is stored in `/home/offline/project/vendor/autoload.php` (two dirs up from the `october` binary).

Can you check if you've got the same values? Are you working from a symlinked directory by chance?

**Comment by alxy** [comment]
Ok, it seems to have been related to my setup yesterday. I tried it now again and it is indeed working with __DIR__ containing the expected path. Thanks!
