### ISSUE TITLE
Octobercms 1.1 not officially released

### ISSUE THREAD

**Issue by obuchmann-pc-web** [OFFLINE-GmbH/oc-bootstrapper#46]
https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/c12161f63a9ccaae938ceeef525bf06e34513fa7/src/Downloader/OctoberCms.php#L58

Am I wrong that Octobercms 1.1 has no official release until now? 
I think we should add a possibility to select the release you want to install via october.yaml. At the moment I know no plugin, that officially supports the 1.1 version of october.

**Comment by tobias-kuendig** [comment]
It looks like it is released (or in the process of being released):
https://october-news.com/october-cms-v110-released

> At the moment I know no plugin, that officially supports the 1.1 version of october.

How many plugins do you use that are broken? Most plugins should work fine, the most common issue will be composer related (too strictly defined dependencies). 

If there are lots of problems I'm open to add an option to select the target version. If it's just a few plugins that will be fixed in a matter of days the effort to implement (and maintain) a new option just isn't worth it.

**Comment by daftspunk** [comment]
It's not officially released yet, but it is available for early testing. October-News is not an official source of information and they jumped the gun

**Comment by tobias-kuendig** [comment]
Alright, thank you @daftspunk. I guess it's safe to stick to the 1.0 branch for now. This is fixed in 0.9.1.

**Comment by damsfx** [comment]
> 
> 
> https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/c12161f63a9ccaae938ceeef525bf06e34513fa7/src/Downloader/OctoberCms.php#L58
> 
> Am I wrong that Octobercms 1.1 has no official release until now?
> I think we should add a possibility to select the release you want to install via october.yaml. At the moment I know no plugin, that officially supports the 1.1 version of october.

I think too!  
In some cases I needed to choose which version of Octobercms to install, the site specific developments (server with PHP 5.5) were not compatible with the latest version of OctoberCms.
